name: pit3_app
description: A new Flutter project.
version: 2.4.6+1
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    bot_toast: ^4.0.1
    common_utils: ^2.1.0
    connectivity_plus: ^2.3.0
    custom_pop_up_menu: ^1.2.3+1
    dio: ^4.0.6
    equatable: ^2.0.2
    event_bus: ^2.0.0
    file_picker: ^4.5.1
    flutter_easyrefresh: ^2.1.5
    flutter_image_compress: ^1.1.0
    flutter_spinkit: ^5.1.0
    get: ^4.3.8
    get_it: ^7.2.0
    image_picker: ^0.8.4+1
    json_annotation: ^3.1.1
    logger: ^1.1.0
    meta: ^1.4.0
    path: ^1.7.0
    path_provider: ^2.0.4
    provider: ^6.0.2
    stacked: ^2.2.5
    qr_code_scanner: ^0.7.0
    responsive_builder: ^0.4.1
    sp_util: ^2.0.3
    sqflite: ^2.0.0+4
    timezone: ^0.8.0
    url_launcher: ^6.0.10
    # 类似 angular 的表单
    reactive_forms: ^11.0.1
    reactive_advanced_switch: ^0.2.0
    # reactive_date_range_picker: ^0.2.0
    reactive_date_time_picker: ^0.2.2
    reactive_dropdown_search: ^0.6.0
    # reactive_flutter_typeahead: ^0.3.0
    # reactive_raw_autocomplete: ^0.1.1
    # reactive_file_picker: ^0.6.0
    # reactive_image_picker: ^0.8.1
    # reactive_multi_image_picker: ^0.5.0
    # reactive_segmented_control: ^0.2.0
    # reactive_signature: ^0.3.0
    # reactive_touch_spin: ^0.4.1
    # reactive_range_slider: ^0.2.0
    # reactive_sleek_circular_slider: ^0.1.0
    # reactive_flutter_rating_bar: ^0.1.0
    # reactive_pinput: ^0.2.0
    # reactive_cupertino_switch: ^0.1.0
    # 图片工具
    extended_image: ^6.0.2+1
    # 文件类型
    mime_type: ^1.0.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    font_awesome_flutter: ^10.1.0
    build_runner: ^1.10.9
    json_serializable: ^3.5.1
flutter:
    uses-material-design: true
    assets:
        - images/no_image.png
        - images/ic_error.png
        - images/ic_empty.png
        - images/default_user_header.png
        - images/logo.png
    fonts:
        - family: Iconfont
          fonts:
              - asset: fonts/iconfont.ttf
    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
